version: '3.1'
services:
 pg-master:
   image: postgres:11.1
   restart: always
   ports:
   - "5432:5432"
   environment:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'postgres'
#    PGDATA: '/var/lib/postgresql/data/pgdata'
#   volumes:
#   - pg_data_master:/
#   - logvolume01:/var/log
#   links:
#   - pg-slave


# pg-slave:
#    image:postgres:11.1

volumes:
  pg_data_master:
